#!/bin/bash

displayFile='/tmp/.displays'
echo " " > "${displayFile}"
case $BLOCK_BUTTON in
  1) echo "intern" > "${displayFile}" && ~/.screenlayout/intern.sh & > /dev/null ;; # left click
  2) echo "clone" > "${displayFile}" && ~/.screenlayout/clone.sh & > /dev/null ;; # middle click
  3) echo "extend" > "${displayFile}" && ~/.screenlayout/extend.sh & > /dev/null ;; # right click
esac
cat "${displayFile}"
